import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faEdit,
  faToggleOn,
  faToggleOff,
  faComment,
  faPlusSquare,
  faMinusSquare,
  faPenFancy,
  faThumbsUp,
  faReply,
  faSave,
  faSignInAlt,
  faSignOutAlt,
  faUndoAlt,
  faImages,
  faUserPlus,
  faUser,
  faCompactDisc,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faEdit,
  faToggleOff,
  faToggleOn,
  faComment,
  faPlusSquare,
  faMinusSquare,
  faPenFancy,
  faThumbsUp,
  faReply,
  faSave,
  faSignInAlt,
  faSignOutAlt,
  faUndoAlt,
  faImages,
  faUserPlus,
  faUser,
  faCompactDisc
);
