const countries = {
  Afghanistan: { name: "Afghanistan", code: "AF" },
  "Åland Islands": { name: "Åland Islands", code: "AX" },
  Albania: { name: "Albania", code: "AL" },
  Algeria: { name: "Algeria", code: "DZ" },
  "American Samoa": { name: "American Samoa", code: "AS" },
  Andorra: { name: "Andorra", code: "AD" },
  Angola: { name: "Angola", code: "AO" },
  Anguilla: { name: "Anguilla", code: "AI" },
  Antarctica: { name: "Antarctica", code: "AQ" },
  "Antigua and Barbuda": { name: "Antigua and Barbuda", code: "AG" },
  Argentina: { name: "Argentina", code: "AR" },
  Armenia: { name: "Armenia", code: "AM" },
  Aruba: { name: "Aruba", code: "AW" },
  Australia: { name: "Australia", code: "AU" },
  Austria: { name: "Austria", code: "AT" },
  Azerbaijan: { name: "Azerbaijan", code: "AZ" },
  Bahamas: { name: "Bahamas", code: "BS" },
  Bahrain: { name: "Bahrain", code: "BH" },
  Bangladesh: { name: "Bangladesh", code: "BD" },
  Barbados: { name: "Barbados", code: "BB" },
  Belarus: { name: "Belarus", code: "BY" },
  Belgium: { name: "Belgium", code: "BE" },
  Belize: { name: "Belize", code: "BZ" },
  Benin: { name: "Benin", code: "BJ" },
  Bermuda: { name: "Bermuda", code: "BM" },
  Bhutan: { name: "Bhutan", code: "BT" },
  "Bolivia, Plurinational State of": {
    name: "Bolivia, Plurinational State of",
    code: "BO",
  },
  "Bonaire, Sint Eustatius and Saba": {
    name: "Bonaire, Sint Eustatius and Saba",
    code: "BQ",
  },
  "Bosnia and Herzegovina": { name: "Bosnia and Herzegovina", code: "BA" },
  Botswana: { name: "Botswana", code: "BW" },
  "Bouvet Island": { name: "Bouvet Island", code: "BV" },
  Brazil: { name: "Brazil", code: "BR" },
  "British Indian Ocean Territory": {
    name: "British Indian Ocean Territory",
    code: "IO",
  },
  "Brunei Darussalam": { name: "Brunei Darussalam", code: "BN" },
  Bulgaria: { name: "Bulgaria", code: "BG" },
  "Burkina Faso": { name: "Burkina Faso", code: "BF" },
  Burundi: { name: "Burundi", code: "BI" },
  Cambodia: { name: "Cambodia", code: "KH" },
  Cameroon: { name: "Cameroon", code: "CM" },
  Canada: { name: "Canada", code: "CA" },
  "Cape Verde": { name: "Cape Verde", code: "CV" },
  "Cayman Islands": { name: "Cayman Islands", code: "KY" },
  "Central African Republic": { name: "Central African Republic", code: "CF" },
  Chad: { name: "Chad", code: "TD" },
  Chile: { name: "Chile", code: "CL" },
  China: { name: "China", code: "CN" },
  "Christmas Island": { name: "Christmas Island", code: "CX" },
  "Cocos (Keeling) Islands": { name: "Cocos (Keeling) Islands", code: "CC" },
  Colombia: { name: "Colombia", code: "CO" },
  Comoros: { name: "Comoros", code: "KM" },
  Congo: { name: "Congo", code: "CG" },
  "Congo, the Democratic Republic of the": {
    name: "Congo, the Democratic Republic of the",
    code: "CD",
  },
  "Cook Islands": { name: "Cook Islands", code: "CK" },
  "Costa Rica": { name: "Costa Rica", code: "CR" },
  "Côte d'Ivoire": { name: "Côte d'Ivoire", code: "CI" },
  Croatia: { name: "Croatia", code: "HR" },
  Cuba: { name: "Cuba", code: "CU" },
  Curaçao: { name: "Curaçao", code: "CW" },
  Cyprus: { name: "Cyprus", code: "CY" },
  "Czech Republic": { name: "Czech Republic", code: "CZ" },
  Denmark: { name: "Denmark", code: "DK" },
  Djibouti: { name: "Djibouti", code: "DJ" },
  Dominica: { name: "Dominica", code: "DM" },
  "Dominican Republic": { name: "Dominican Republic", code: "DO" },
  Ecuador: { name: "Ecuador", code: "EC" },
  Egypt: { name: "Egypt", code: "EG" },
  "El Salvador": { name: "El Salvador", code: "SV" },
  "Equatorial Guinea": { name: "Equatorial Guinea", code: "GQ" },
  Eritrea: { name: "Eritrea", code: "ER" },
  Estonia: { name: "Estonia", code: "EE" },
  Ethiopia: { name: "Ethiopia", code: "ET" },
  Europe: { name: "Europe", code: "EU" },
  "Falkland Islands (Malvinas)": {
    name: "Falkland Islands (Malvinas)",
    code: "FK",
  },
  "Faroe Islands": { name: "Faroe Islands", code: "FO" },
  Fiji: { name: "Fiji", code: "FJ" },
  Finland: { name: "Finland", code: "FI" },
  France: { name: "France", code: "FR" },
  "French Guiana": { name: "French Guiana", code: "GF" },
  "French Polynesia": { name: "French Polynesia", code: "PF" },
  "French Southern Territories": {
    name: "French Southern Territories",
    code: "TF",
  },
  Gabon: { name: "Gabon", code: "GA" },
  Gambia: { name: "Gambia", code: "GM" },
  Georgia: { name: "Georgia", code: "GE" },
  Germany: { name: "Germany", code: "DE" },
  Ghana: { name: "Ghana", code: "GH" },
  Gibraltar: { name: "Gibraltar", code: "GI" },
  Greece: { name: "Greece", code: "GR" },
  Greenland: { name: "Greenland", code: "GL" },
  Grenada: { name: "Grenada", code: "GD" },
  Guadeloupe: { name: "Guadeloupe", code: "GP" },
  Guam: { name: "Guam", code: "GU" },
  Guatemala: { name: "Guatemala", code: "GT" },
  Guernsey: { name: "Guernsey", code: "GG" },
  Guinea: { name: "Guinea", code: "GN" },
  "Guinea-Bissau": { name: "Guinea-Bissau", code: "GW" },
  Guyana: { name: "Guyana", code: "GY" },
  Haiti: { name: "Haiti", code: "HT" },
  "Heard Island and McDonald Islands": {
    name: "Heard Island and McDonald Islands",
    code: "HM",
  },
  "Holy See (Vatican City State)": {
    name: "Holy See (Vatican City State)",
    code: "VA",
  },
  Honduras: { name: "Honduras", code: "HN" },
  "Hong Kong": { name: "Hong Kong", code: "HK" },
  Hungary: { name: "Hungary", code: "HU" },
  Iceland: { name: "Iceland", code: "IS" },
  India: { name: "India", code: "IN" },
  Indonesia: { name: "Indonesia", code: "ID" },
  "Iran, Islamic Republic of": {
    name: "Iran, Islamic Republic of",
    code: "IR",
  },
  Iraq: { name: "Iraq", code: "IQ" },
  Ireland: { name: "Ireland", code: "IE" },
  "Isle of Man": { name: "Isle of Man", code: "IM" },
  Israel: { name: "Israel", code: "IL" },
  Italy: { name: "Italy", code: "IT" },
  Jamaica: { name: "Jamaica", code: "JM" },
  Japan: { name: "Japan", code: "JP" },
  Jersey: { name: "Jersey", code: "JE" },
  Jordan: { name: "Jordan", code: "JO" },
  Kazakhstan: { name: "Kazakhstan", code: "KZ" },
  Kenya: { name: "Kenya", code: "KE" },
  Kiribati: { name: "Kiribati", code: "KI" },
  "Korea, Democratic People's Republic of": {
    name: "Korea, Democratic People's Republic of",
    code: "KP",
  },
  "Korea, Republic of": { name: "Korea, Republic of", code: "KR" },
  Kuwait: { name: "Kuwait", code: "KW" },
  Kyrgyzstan: { name: "Kyrgyzstan", code: "KG" },
  "Lao People's Democratic Republic": {
    name: "Lao People's Democratic Republic",
    code: "LA",
  },
  Latvia: { name: "Latvia", code: "LV" },
  Lebanon: { name: "Lebanon", code: "LB" },
  Lesotho: { name: "Lesotho", code: "LS" },
  Liberia: { name: "Liberia", code: "LR" },
  Libya: { name: "Libya", code: "LY" },
  Liechtenstein: { name: "Liechtenstein", code: "LI" },
  Lithuania: { name: "Lithuania", code: "LT" },
  Luxembourg: { name: "Luxembourg", code: "LU" },
  Macao: { name: "Macao", code: "MO" },
  "Macedonia, the Former Yugoslav Republic of": {
    name: "Macedonia, the Former Yugoslav Republic of",
    code: "MK",
  },
  Madagascar: { name: "Madagascar", code: "MG" },
  Malawi: { name: "Malawi", code: "MW" },
  Malaysia: { name: "Malaysia", code: "MY" },
  Maldives: { name: "Maldives", code: "MV" },
  Mali: { name: "Mali", code: "ML" },
  Malta: { name: "Malta", code: "MT" },
  "Marshall Islands": { name: "Marshall Islands", code: "MH" },
  Martinique: { name: "Martinique", code: "MQ" },
  Mauritania: { name: "Mauritania", code: "MR" },
  Mauritius: { name: "Mauritius", code: "MU" },
  Mayotte: { name: "Mayotte", code: "YT" },
  Mexico: { name: "Mexico", code: "MX" },
  "Micronesia, Federated States of": {
    name: "Micronesia, Federated States of",
    code: "FM",
  },
  "Moldova, Republic of": { name: "Moldova, Republic of", code: "MD" },
  Monaco: { name: "Monaco", code: "MC" },
  Mongolia: { name: "Mongolia", code: "MN" },
  Montenegro: { name: "Montenegro", code: "ME" },
  Montserrat: { name: "Montserrat", code: "MS" },
  Morocco: { name: "Morocco", code: "MA" },
  Mozambique: { name: "Mozambique", code: "MZ" },
  Myanmar: { name: "Myanmar", code: "MM" },
  Namibia: { name: "Namibia", code: "NA" },
  Nauru: { name: "Nauru", code: "NR" },
  Nepal: { name: "Nepal", code: "NP" },
  Netherlands: { name: "Netherlands", code: "NL" },
  "New Caledonia": { name: "New Caledonia", code: "NC" },
  "New Zealand": { name: "New Zealand", code: "NZ" },
  Nicaragua: { name: "Nicaragua", code: "NI" },
  Niger: { name: "Niger", code: "NE" },
  Nigeria: { name: "Nigeria", code: "NG" },
  Niue: { name: "Niue", code: "NU" },
  "Norfolk Island": { name: "Norfolk Island", code: "NF" },
  "Northern Mariana Islands": { name: "Northern Mariana Islands", code: "MP" },
  Norway: { name: "Norway", code: "NO" },
  Oman: { name: "Oman", code: "OM" },
  Pakistan: { name: "Pakistan", code: "PK" },
  Palau: { name: "Palau", code: "PW" },
  "Palestine, State of": { name: "Palestine, State of", code: "PS" },
  Panama: { name: "Panama", code: "PA" },
  "Papua New Guinea": { name: "Papua New Guinea", code: "PG" },
  Paraguay: { name: "Paraguay", code: "PY" },
  Peru: { name: "Peru", code: "PE" },
  Philippines: { name: "Philippines", code: "PH" },
  Pitcairn: { name: "Pitcairn", code: "PN" },
  Poland: { name: "Poland", code: "PL" },
  Portugal: { name: "Portugal", code: "PT" },
  "Puerto Rico": { name: "Puerto Rico", code: "PR" },
  Qatar: { name: "Qatar", code: "QA" },
  Réunion: { name: "Réunion", code: "RE" },
  Romania: { name: "Romania", code: "RO" },
  "Russian Federation": { name: "Russian Federation", code: "RU" },
  Rwanda: { name: "Rwanda", code: "RW" },
  "Saint Barthélemy": { name: "Saint Barthélemy", code: "BL" },
  "Saint Helena, Ascension and Tristan da Cunha": {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    code: "SH",
  },
  "Saint Kitts and Nevis": { name: "Saint Kitts and Nevis", code: "KN" },
  "Saint Lucia": { name: "Saint Lucia", code: "LC" },
  "Saint Martin (French part)": {
    name: "Saint Martin (French part)",
    code: "MF",
  },
  "Saint Pierre and Miquelon": {
    name: "Saint Pierre and Miquelon",
    code: "PM",
  },
  "Saint Vincent and the Grenadines": {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
  },
  Samoa: { name: "Samoa", code: "WS" },
  "San Marino": { name: "San Marino", code: "SM" },
  "Sao Tome and Principe": { name: "Sao Tome and Principe", code: "ST" },
  "Saudi Arabia": { name: "Saudi Arabia", code: "SA" },
  Senegal: { name: "Senegal", code: "SN" },
  Serbia: { name: "Serbia", code: "RS" },
  Seychelles: { name: "Seychelles", code: "SC" },
  "Sierra Leone": { name: "Sierra Leone", code: "SL" },
  Singapore: { name: "Singapore", code: "SG" },
  "Sint Maarten (Dutch part)": {
    name: "Sint Maarten (Dutch part)",
    code: "SX",
  },
  Slovakia: { name: "Slovakia", code: "SK" },
  Slovenia: { name: "Slovenia", code: "SI" },
  "Solomon Islands": { name: "Solomon Islands", code: "SB" },
  Somalia: { name: "Somalia", code: "SO" },
  "South Africa": { name: "South Africa", code: "ZA" },
  "South Georgia and the South Sandwich Islands": {
    name: "South Georgia and the South Sandwich Islands",
    code: "GS",
  },
  "South Sudan": { name: "South Sudan", code: "SS" },
  Spain: { name: "Spain", code: "ES" },
  "Sri Lanka": { name: "Sri Lanka", code: "LK" },
  Sudan: { name: "Sudan", code: "SD" },
  Suriname: { name: "Suriname", code: "SR" },
  "Svalbard and Jan Mayen": { name: "Svalbard and Jan Mayen", code: "SJ" },
  Swaziland: { name: "Swaziland", code: "SZ" },
  Sweden: { name: "Sweden", code: "SE" },
  Switzerland: { name: "Switzerland", code: "CH" },
  "Syrian Arab Republic": { name: "Syrian Arab Republic", code: "SY" },
  "Taiwan, Province of China": {
    name: "Taiwan, Province of China",
    code: "TW",
  },
  Tajikistan: { name: "Tajikistan", code: "TJ" },
  "Tanzania, United Republic of": {
    name: "Tanzania, United Republic of",
    code: "TZ",
  },
  Thailand: { name: "Thailand", code: "TH" },
  "Timor-Leste": { name: "Timor-Leste", code: "TL" },
  Togo: { name: "Togo", code: "TG" },
  Tokelau: { name: "Tokelau", code: "TK" },
  Tonga: { name: "Tonga", code: "TO" },
  "Trinidad and Tobago": { name: "Trinidad and Tobago", code: "TT" },
  Tunisia: { name: "Tunisia", code: "TN" },
  Turkey: { name: "Turkey", code: "TR" },
  Turkmenistan: { name: "Turkmenistan", code: "TM" },
  "Turks and Caicos Islands": { name: "Turks and Caicos Islands", code: "TC" },
  Tuvalu: { name: "Tuvalu", code: "TV" },
  Uganda: { name: "Uganda", code: "UG" },
  Ukraine: { name: "Ukraine", code: "UA" },
  "United Arab Emirates": { name: "United Arab Emirates", code: "AE" },
  "United Kingdom": { name: "United Kingdom", code: "GB" },
  "United States": { name: "United States", code: "US" },
  "United States Minor Outlying Islands": {
    name: "United States Minor Outlying Islands",
    code: "UM",
  },
  Uruguay: { name: "Uruguay", code: "UY" },
  Uzbekistan: { name: "Uzbekistan", code: "UZ" },
  Vanuatu: { name: "Vanuatu", code: "VU" },
  "Venezuela, Bolivarian Republic of": {
    name: "Venezuela, Bolivarian Republic of",
    code: "VE",
  },
  "Viet Nam": { name: "Viet Nam", code: "VN" },
  "Virgin Islands, British": { name: "Virgin Islands, British", code: "VG" },
  "Virgin Islands, U.S.": { name: "Virgin Islands, U.S.", code: "VI" },
  "Wallis and Futuna": { name: "Wallis and Futuna", code: "WF" },
  "Western Sahara": { name: "Western Sahara", code: "EH" },
  Yemen: { name: "Yemen", code: "YE" },
  Zambia: { name: "Zambia", code: "ZM" },
  Zimbabwe: { name: "Zimbabwe", code: "ZW" },
};

module.exports = countries;
